### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
deepspeed: /home/h/huyle/projects/robospatial2/robospatial2-training/configs/ds_z3_config.json

### dataset
dataset: hope_train
eval_dataset: hope_val
dataset_dir: data
template: qwen2_vl
cutoff_len: 2048
max_samples: 100392
overwrite_cache: true
preprocessing_num_workers: 40
dataloader_num_workers: 2


### output
output_dir: /scratch/h/huyle/weights/robospatial2/qwen2_5vl-7B/full/sft
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]
run_name: rs2_qwen2_5vl-7B-sft_16gpus

### train
per_device_train_batch_size: 48
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
#val_size: 0.1
per_device_eval_batch_size: 48
eval_strategy: steps
eval_steps: 1000