### model
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
deepspeed: /project/aip-agrawal/huyle/projects/robospatial2/robospatial2-training/configs/ds_z3_config.json

### dataset - Using preprocessed tokenized data for faster training startup
tokenized_path: /project/6100855/huyle/projects/robospatial2/robospatial2-training/preprocessed_data/qwen2_5vl-3b-hope
# Note: When using tokenized_path, the following dataset parameters are ignored:
# dataset, eval_dataset, dataset_dir, template, cutoff_len, overwrite_cache, preprocessing_num_workers
# But we still need media_dir for loading images
media_dir: /project/aip-agrawal/huyle/projects/robospatial2/robospatial2-training/dataset
dataloader_num_workers: 8
seed: 42

### output
output_dir: /scratch/h/huyle/weights/robospatial2/qwen2_5vl-3b/full/sft/16gpus/2Msamples
logging_steps: 10
save_strategy: epoch
# save_strategy: steps
# save_steps: 1
plot_loss: true
overwrite_output_dir: true
# load_best_model_at_end: false
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]
run_name: rs2_qwen2_5vl-3b-sft_1e5_16gpus_2Msamples

### train
per_device_train_batch_size: 48
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
# resume_from_checkpoint: /scratch/h/huyle/weights/robospatial2/qwen2_5vl-3b/full/sft/checkpoint-264
resume_from_checkpoint: null

### eval
#val_size: 0.1
per_device_eval_batch_size: 48
eval_strategy: epoch
# eval_steps: 1
